name: Build site

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: dist
