name: Deploy to demos.noenieto.com

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Build the site
        run: yarn build
      - name: Rsync the build
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          src: build/
          # Remote server and path. i.e user@server.com:/var/www/server.com/
          dest: ${{secrets.RSYNC_DEST}}


